/**
 * dy not like 
 * TO Entities for managing Chat results - ENTITES DEFINED FOR DIFFERENT SQLLITE DATABASES
 * Depends on pk-ts-sqlite-lib
 */

import "reflect-metadata";
import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn,
  BaseEntity, Point, BeforeInsert, AfterInsert, RelationOptions, AfterLoad,

  OneToMany, ManyToMany, ManyToOne, JoinColumn, JoinTable, OneToOne, type Relation,
} from "typeorm";
import { PkError, GenObj, isEmpty, typeOf, isObject, isSimpleObject,
  getClass,

}
  from 'pk-ts-common-lib';

import _ from 'lodash';
import { PkBaseEntity, PkBaseUser, } from "pk-ts-sqlite-lib/typeorm";
import { IsIn, IsOptional, IsDate, validate, } from 'class-validator';

// Local Imports

import {stripComments,} from '../init.js';

// Get valid arrays of values like qualtiy, unit, etc.

let cascade: RelationOptions = { cascade: true, };


/**
 * Entity to capture function details/metadata generated by chats
 * FOR Indivual Chat Results for different models, in different DBs
 */

@Entity() export class FunctionDets extends PkBaseEntity {
  @Column({ nullable: true }) library: string;
  @Column({ nullable: true }) model: string;
  @Column({ nullable: true }) file: string;
  @Column({ nullable: true }) type: string;
  @Column({ nullable: true, default: 'typescript' }) language: string;
  @Column({ nullable: true }) name: string;
  //@Column({ nullable: true, type:'text', }) body: string;
  @Column({ nullable: true, length: 9000, }) body: string;
  @Column({ nullable: true, type: 'json' }) metadata; //The JSON stringified metadata object
  @Column({ nullable: true, type: 'json' }) error; //Reported error/exception
  @Column({ nullable: true, type: 'text' }) signature: string;
  @Column({ nullable: true, type: 'text', }) params: string;
  @Column({ nullable: true, type: 'text' }) return: string;
  @Column({ nullable: true, type: 'text' }) description: string;
  @Column({ nullable: true, type: 'text' }) examples: string;
  @Column({ nullable: true, type: 'text' }) todos: string;
  static async fncsNoBody() {
    let fncs = await this.find({ where: { type: 'function', body: null, }, });
    return fncs;
  }
  /** Get functions with no body, or body that is not a typescript code block */
  static async fncsNoTsBody() {
    let qb = this.newQueryBuilder();
    qb.where('type = "function" AND ( body not like "```typescript%" OR body is null )');
    let fncs = await qb.getMany();
    return fncs;
  }
  static async fncByName(name: string) {
    let fncs = await this.find({ where: { type: 'function', name, }, });
    if (fncs.length === 0) {
      throw new Error(`No function named ${name}`);
    }
    return fncs[0];
  }
};
@Entity() export class LogItem extends PkBaseEntity {
  @Column({ nullable: true }) model: string;
  @Column({ nullable: true }) agent: string;
  @Column({ nullable: true }) provider: string;
  @Column({ nullable: true }) chatstamp: string;
  @Column({ nullable: true, type: 'json' }) config;
  @Column({ nullable: true, type: 'json' }) error; //Reported error/exception
  @Column({ nullable: true, type: 'json' }) opts;
  @Column({ nullable: true, type: 'json' }) messages;
  @Column({ nullable: true, type: 'text' }) content;
  @Column({ nullable: true, type: 'json' }) response;
  @Column({ nullable: true, type: 'text' }) assistant;
};

// DB Entities for capturing chat results 

@Entity() export class ChatLog extends PkBaseEntity {

  @Column({ nullable: true }) label: string;
  @Column({ nullable: true }) model: string;
  @Column({ nullable: true }) provider: string;
  @Column({ nullable: true }) stamp: string;
  @Column({ nullable: true, type: 'text' }) outpath;
  @Column({ nullable: true, type: 'text' }) chatinfo;
  @Column({ nullable: true, type: 'text' }) usrmsg;
  @Column({ nullable: true, type: 'text' }) sysmsg;

  @Column({ nullable: true, type: 'text' }) assistant;
  @Column({ nullable: true, type: 'json' }) createparams;
  @Column({ nullable: true, type: 'json' }) chatconfig;
  @Column({ nullable: true, type: 'json' }) response;
  @OneToMany(() => ChatItem, (chat_item) => chat_item.chat_log, { cascade: true, }) chat_items: ChatItem[];

  async addChatItem(chat_item: any) {
    if (isSimpleObject(chat_item)) {
      //@ts-ignore
      //chat_item = new ChatItem(chat_item);
      chat_item = ChatItem.create(chat_item);
    }
    if (!(chat_item instanceof ChatItem)) {
      throw new PkError(`chat_item neither simple object or ChatItem instance`, { chat_item });
    }
    chat_item.chat_log = this;
    //console.log(`In addChatItem -`, chat_item);
    await chat_item.save();
    await this.save();
    return chat_item;
  }
}

// Records each exchange of a chat session - user msg & assistant response
@Entity() export class ChatItem extends PkBaseEntity {
  @Column({ nullable: true }) chatstamp: string;
  @Column({ nullable: true, type: 'text' }) usrmsg;
  @Column({ nullable: true, type: 'text' }) chatinfo;
  @Column({ nullable: true, type: 'text' }) sysmsg;
  @Column({ nullable: true, type: 'text' }) assistant;
  @Column({ nullable: true, type: 'text' }) pycode;
  @Column({ nullable: true, type: 'text' }) tscode;
  @Column({ nullable: true, type: 'json' }) extra;
  @Column({ nullable: true, type: 'json' }) response;
  @Column({ nullable: true, type: 'json' }) messages;
  @ManyToOne(() => ChatLog, (chat_log) => chat_log.chat_items,) chat_log: ChatLog;
}

export enum MsgType {
  sys = 'sys',
  usr = 'usr',
};

export enum EntType {
  msg = 'msg',
  code = 'code',
};

/**
 * Entity for building messages for chat sessions
 */
@Entity() export class MsgBuilder extends PkBaseEntity {
  @Column({ unique: true }) key: string;
  @Column({ type: 'simple-enum', enum: EntType, }) enttype: EntType;
  @Column({ nullable: true, type: 'simple-enum', enum: MsgType, }) msgtype: MsgType;
  @Column({ nullable: true, type: 'text', }) body: string;
  @Column({ nullable: true, type: 'text', }) expanded: string;
  @Column({ nullable: true, type: 'json', }) codeobj;
  //@Column({ nullable: true, type: 'json', default: [] }) parentKeys;
  @Column({ nullable: true, type: 'json', }) parentKeys;
  @Column({ nullable: true, type: 'json', }) normParentKeys;
  @ManyToMany(() => MsgBuilder, (msg) => msg.ancestors)
  @JoinTable({
    name: "msg_ancestors", // Name of the join table
    joinColumn: {
      name: "ancestor_key", // Column in the join table referencing the subordinate
      referencedColumnName: "key", // References the `email` field in the Employee entity
    },
    inverseJoinColumn: {
      name: "descendant_key", // Column in the join table referencing the manager
      referencedColumnName: "key", // References the `email` field in the Employee entity
    },
  })
  ancestors: MsgBuilder[];

  /**
   * Subordinates of the employee. This is a many-to-many self-referential relationship.
   */
  @ManyToMany(() => MsgBuilder, (msg) => msg.ancestors)
  descendants: MsgBuilder[];

  // Instance methods
  async addParentKey(parentKey: string) {
    if (!this.parentKeys) {
      this.parentKeys = [];
    }
    if (this.parentKeys.includes(parentKey)) {
      return;
    }
    this.parentKeys.push(parentKey);
    await this.save();
  }

  async assembleParentKeys(depth = 0) {
    depth++;
    let assKeys: string[] = [];
    for (let parentKey of this.parentKeys) {
      let parentMsg = await MsgBuilder.findByKey(parentKey);
      let pparentKeys = parentMsg.parentKeys;
      for (let pparentKey of pparentKeys) {
        let ppMsg = await MsgBuilder.findByKey(pparentKey);
        let tmpAssKeys = await ppMsg.assembleParentKeys(depth);
        for (let tmpAssKey of tmpAssKeys) {
          if (!assKeys.includes(tmpAssKey)) {
            assKeys.push(tmpAssKey);
          }
        }
        if (!assKeys.includes(pparentKey)) {
          assKeys.push(pparentKey);
        }
      }
      if (!assKeys.includes(parentKey)) {
        assKeys.push(parentKey);
      }
    }
    console.log(`Return assembleParentKeys: msgKey: [${this.key}], depth: [${depth}], parentKeys:`, this.parentKeys);
    return assKeys;
  }

  // Strip msg embeds (NOT Code embeds) from msg.body. Also comments.
  /*
  */
  async stripMsgEmbeds() {
    //let msgKeys = await (this.constructor as InstanceType<typeof this.constructor>).getMsgKeys('msg');
    let stripped = this.body;
    //let msgKeys = await (this.constructor as GenObj).getMsgKeys('msg');
    //let msgKeys = await (getClass(this)).getMsgKeys('msg');
    //let msgKeys = await getClass(this).getMsgKeys('msg');
    /*
    let cName = this.class.name;
    console.log(`in stripMsgEmbeds - cName: [${cName}]`);
    */
    let msgKeys = await this.class.getMsgKeys('msg');
    let msgEmbeds = msgKeys.map(msgKey => `[[${msgKey}]]`);
    for (let msgEmbed of msgEmbeds) {
      stripped = stripped.replaceAll(msgEmbed, '');
    }
    stripped = stripComments(stripped);
    return stripped;
  }
  /*
    */
  async assembleMsg(depth = 0) {
    let assKeys = await this.assembleParentKeys(depth);
    let assMsg = '';
    for (let assKey of assKeys) {
      let assMsgPart = await MsgBuilder.findByKey(assKey);
      if (assMsgPart) {
        //assMsg += await assMsgPart.body;
        assMsg += `\n\n${await assMsgPart.stripMsgEmbeds()}\n\n`;
      }
    }
    //assMsg += this.body;
    assMsg += `\n\n${await this.stripMsgEmbeds()}\n\n`;
    return assMsg;
  }

  //static methods
  static findByKey<T extends BaseEntity>(
    this: { new(): T; } & typeof BaseEntity,
    key: string,
  ): Promise<T | null> {
    // @ts-ignore
    return this.getRepository<T>().findOneBy({ key });
  }
  /**
   * Get all keys of a given type where msgType one of `code`, `usr`, 'sys', 'msg', 'all'
   */
  static async getMsgs(msgType?: string) {
    if (!msgType) {
      msgType = 'all';
    }
    let where: GenObj = {};
    switch (msgType) {
      case 'all':
        break;
      case 'msg':
        where.enttype = EntType.msg;
        break;
      case 'code':
        where.enttype = EntType.code;
        break;
      case 'usr':
        where.msgtype = MsgType.usr;
        break;
      case 'sys':
        where.msgtype = MsgType.sys;
        break;
    }
    return this.find({ where });
  }
  static async getMsgKeys(msgType?: string) {
    let msgs = await this.getMsgs(msgType);
    return msgs.map(m => m.key);
  }
}


/* 
 * FOR System Log Entries
*/

export const chatEntities = { ChatLog, ChatItem, };
export const fncEntities = {
  FunctionDets,
};

export const logEntities = {
  LogItem,
};
